### ISSUE TITLE
Project Setup: Initialize Repository and Base Structure

### ISSUE THREAD

**Issue by asxs7** [asxs7/test-repo#2]
Set up the initial project structure and configure GitHub Pages deployment.

### Tasks
- [ ] Initialize the repository with necessary files:
  - `index.html`
  - `styles.css`
  - `app.js`
  - `README.md`
- [ ] Set up GitHub Pages deployment
- [ ] Configure the base HTML structure with proper meta tags and responsive viewport settings
- [ ] Add CDN links for required libraries:
  - PapaParse.js
  - Chart.js
  - Selected font family (Poppins or Inter)
- [ ] Create initial README.md with project description and setup instructions
- [ ] Implement basic color palette CSS variables:
  ```css
  :root {
    --primary: #DC6D18;
    --background: #FFF4E4;
    --table-highlight: #F8E0C9;
    --text: #2B1A12;
    --border: #B1AA81;
  }
  ```

### Acceptance Criteria
- [ ] Repository is created and accessible
- [ ] GitHub Pages is properly configured and displaying a basic page
- [ ] All necessary dependencies are properly linked
- [ ] Color palette is implemented and accessible via CSS variables
- [ ] README.md contains basic project information
- [ ] Base HTML structure is semantic and validates without errors
