### ISSUE TITLE
Create Initial Project Files

### ISSUE THREAD

**Issue by asxs7** [asxs7/test-repo#4]
Creating the initial project files with fresh code. Please commit these files to the repository.

### index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Data Visualization Dashboard">
    <title>Data Visualization Dashboard</title>
    
    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap" rel="stylesheet">
    
    <!-- External Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/papaparse@5.3.0/papaparse.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    
    <!-- Custom CSS -->
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>Data Visualization Dashboard</h1>
            <div class="upload-section">
                <input type="file" id="csvFile" accept=".csv" class="file-input">
                <label for="csvFile" class="file-label">Choose CSV File</label>
            </div>
        </header>

        <main class="main-content">
            <section class="visualization-section">
                <div class="chart-container">
                    <canvas id="dataChart"></canvas>
                </div>
            </section>

            <section class="data-section">
                <div class="table-container">
                    <table id="dataTable">
                        <thead>
                            <tr>
                                <!-- Table headers will be dynamically added -->
                            </tr>
                        </thead>
                        <tbody>
                            <!-- Table data will be dynamically added -->
                        </tbody>
                    </table>
                </div>
            </section>
        </main>

        <footer class="footer">
            <p>© 2025 Data Visualization Project</p>
        </footer>
    </div>

    <!-- Custom JavaScript -->
    <script src="app.js"></script>
</body>
</html>
```

### styles.css
```css
:root {
    --primary: #DC6D18;
    --background: #FFF4E4;
    --table-highlight: #F8E0C9;
    --text: #2B1A12;
    --border: #B1AA81;
    --white: #FFFFFF;
    --shadow: rgba(0, 0, 0, 0.1);
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Poppins', sans-serif;
    background-color: var(--background);
    color: var(--text);
    line-height: 1.6;
    min-height: 100vh;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    padding: 20px;
}

.header {
    background-color: var(--primary);
    color: var(--white);
    padding: 2rem;
    border-radius: 10px;
    margin-bottom: 2rem;
    text-align: center;
    box-shadow: 0 4px 6px var(--shadow);
}

.upload-section {
    margin-top: 1.5rem;
}

.file-input {
    display: none;
}

.file-label {
    background-color: var(--white);
    color: var(--primary);
    padding: 0.8rem 1.5rem;
    border-radius: 5px;
    cursor: pointer;
    transition: all 0.3s ease;
    display: inline-block;
}

.file-label:hover {
    background-color: var(--table-highlight);
}

.main-content {
    display: grid;
    gap: 2rem;
    margin-bottom: 2rem;
}

.visualization-section,
.data-section {
    background-color: var(--white);
    border-radius: 10px;
    padding: 1.5rem;
    box-shadow: 0 4px 6px var(--shadow);
}

.chart-container {
    width: 100%;
    height: 400px;
    position: relative;
}

.table-container {
    overflow-x: auto;
}

table {
    width: 100%;
    border-collapse: collapse;
    margin-top: 1rem;
}

th, td {
    padding: 0.8rem;
    text-align: left;
    border-bottom: 1px solid var(--border);
}

th {
    background-color: var(--primary);
    color: var(--white);
}

tr:nth-child(even) {
    background-color: var(--table-highlight);
}

.footer {
    text-align: center;
    padding: 1rem;
    color: var(--text);
    border-top: 1px solid var(--border);
}

@media (max-width: 768px) {
    .container {
        padding: 10px;
    }
    
    .header {
        padding: 1.5rem;
    }
    
    .main-content {
        gap: 1rem;
    }
    
    .chart-container {
        height: 300px;
    }
}
```

### app.js
```javascript
document.addEventListener('DOMContentLoaded', function() {
    // DOM Elements
    const fileInput = document.getElementById('csvFile');
    const dataTable = document.getElementById('dataTable');
    const chartCanvas = document.getElementById('dataChart');
    
    let chart = null; // Store chart instance
    
    // File input change handler
    fileInput.addEventListener('change', handleFileSelect);
    
    // Handle file selection
    function handleFileSelect(event) {
        const file = event.target.files[0];
        if (file) {
            parseCSV(file);
        }
    }
    
    // Parse CSV file
    function parseCSV(file) {
        Papa.parse(file, {
            header: true,
            complete: function(results) {
                if (results.data && results.data.length > 0) {
                    displayData(results.data);
                    createVisualization(results.data);
                }
            },
            error: function(error) {
                console.error('Error parsing CSV:', error);
                alert('Error parsing CSV file. Please check the file format.');
            }
        });
    }
    
    // Display data in table
    function displayData(data) {
        // Clear existing table content
        dataTable.innerHTML = '';
        
        // Create table header
        const thead = document.createElement('thead');
        const headerRow = document.createElement('tr');
        Object.keys(data[0]).forEach(key => {
            const th = document.createElement('th');
            th.textContent = key;
            headerRow.appendChild(th);
        });
        thead.appendChild(headerRow);
        dataTable.appendChild(thead);
        
        // Create table body
        const tbody = document.createElement('tbody');
        data.forEach(row => {
            const tr = document.createElement('tr');
            Object.values(row).forEach(value => {
                const td = document.createElement('td');
                td.textContent = value;
                tr.appendChild(td);
            });
            tbody.appendChild(tr);
        });
        dataTable.appendChild(tbody);
    }
    
    // Create visualization
    function createVisualization(data) {
        // Destroy existing chart if it exists
        if (chart) {
            chart.destroy();
        }
        
        // Get the first numeric column for visualization
        const columns = Object.keys(data[0]);
        const numericColumn = columns.find(column => 
            !isNaN(data[0][column]) && data[0][column] !== ''
        );
        
        if (!numericColumn) {
            console.error('No numeric columns found for visualization');
            return;
        }
        
        // Prepare data for chart
        const chartData = {
            labels: data.map((row, index) => `Row ${index + 1}`),
            datasets: [{
                label: numericColumn,
                data: data.map(row => parseFloat(row[numericColumn])),
                backgroundColor: 'rgba(220, 109, 24, 0.2)',
                borderColor: 'rgba(220, 109, 24, 1)',
                borderWidth: 1
            }]
        };
        
        // Create new chart
        chart = new Chart(chartCanvas, {
            type: 'bar',
            data: chartData,
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                },
                plugins: {
                    title: {
                        display: true,
                        text: `Data Visualization - ${numericColumn}`
                    }
                }
            }
        });
    }
});
```

### README.md
```markdown
# Data Visualization Dashboard

A web-based data visualization tool that allows users to upload CSV files and view the data in both tabular and chart formats.

## Features

- CSV file parsing using PapaParse.js
- Interactive data visualization using Chart.js
- Responsive design with custom color palette
- Tabular data display
- Modern UI with custom styling

## Setup

1. Clone the repository:
```bash
git clone https://github.com/asxs7/test-repo.git
cd test-repo
```

2. Open `index.html` in your web browser to run the application locally.

## Usage

1. Click the "Choose CSV File" button to upload your CSV file
2. The data will be displayed in a table format below the chart
3. The first numeric column in your CSV will be automatically visualized in the chart
4. The visualization is responsive and will adjust to your screen size

## Color Palette

The project uses a custom color palette defined in CSS variables:
- Primary: `#DC6D18`
- Background: `#FFF4E4`
- Table Highlight: `#F8E0C9`
- Text: `#2B1A12`
- Border: `#B1AA81`

## Dependencies

- [PapaParse.js](https://www.papaparse.com/) - CSV parsing
- [Chart.js](https://www.chartjs.org/) - Data visualization
- [Google Fonts (Poppins)](https://fonts.google.com/specimen/Poppins) - Typography

## Browser Support

The dashboard is compatible with modern browsers including:
- Chrome
- Firefox
- Safari
- Edge

## Contributing

1. Fork the repository
2. Create your feature branch: `git checkout -b feature/NewFeature`
3. Commit your changes: `git commit -m 'Add NewFeature'`
4. Push to the branch: `git push origin feature/NewFeature`
5. Submit a pull request

## License

This project is open source and available under the MIT License.
```

Please let me know if you'd like me to:
1. Create a new pull request with these files
2. Help you commit them directly to the main branch
3. Guide you through the process of adding them manually
